server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Przekazuje API do backendu w k8s
    location /api/ {
        proxy_pass http://backend-service:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback — React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
