"""Argon2id password hashing using ``argon2-cffi``.

The salt is generated by the library (16 bytes, per-hash) and embedded in
the encoded string — no separate column needed. ``needs_rehash`` allows
silent parameter upgrades when the workload constants change.
"""

from __future__ import annotations

from argon2 import PasswordHasher, exceptions
from argon2.profiles import RFC_9106_LOW_MEMORY

from app.modules.identity.application.ports import IPasswordHasher


class Argon2Hasher(IPasswordHasher):
    """Concrete ``IPasswordHasher`` using Argon2id (RFC 9106, low-memory profile)."""

    def __init__(self) -> None:
        self._ph = PasswordHasher.from_parameters(RFC_9106_LOW_MEMORY)

    def hash(self, plain: str) -> str:
        return self._ph.hash(plain)

    def verify(self, hashed: str, plain: str) -> bool:
        if not hashed:
            return False
        try:
            return self._ph.verify(hashed, plain)
        except (exceptions.VerifyMismatchError, exceptions.InvalidHashError):
            return False
        except exceptions.VerificationError:
            return False

    def needs_rehash(self, hashed: str) -> bool:
        try:
            return self._ph.check_needs_rehash(hashed)
        except exceptions.InvalidHashError:
            # Legacy bcrypt hash or some other format — yes, rehash.
            return True
